version: 2

project_name: theorem-mesh

builds:
  - id: theorem-mesh
    dir: client
    binary: theorem-mesh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      - load_wgnt_from_rsrc
    ldflags:
      - >-
        -s -w
        -X github.com/netbirdio/netbird/version.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.CommitDate}}
        -X main.builtBy=theorem-sa
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - id: theorem-mesh-universal
    ids:
      - theorem-mesh
    name_template: theorem-mesh
    replace: true

archives:
  - id: theorem-mesh
    ids:
      - theorem-mesh
      - theorem-mesh-universal
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  use: git

release:
  github:
    owner: theorem-sa
    name: mesh
  draft: true
